# -*- coding: utf-8 -*-
"""Genera CSV del backlog y de la matriz de 15 factores."""
import csv
from pathlib import Path

OUT = Path(__file__).resolve().parent

EPICS = [
    ("E1", "Épica", "E1 — Identidad y acceso", "", "", "",
     "Registrar, autenticar y autorizar usuarios de la plataforma.",
     "", "1", "", "Pendiente", "servicio-identidad; cliente-web", "5; 15", "epica"),
    ("E2", "Épica", "E2 — Gestión de empresas", "", "", "",
     "CRUD de empresas con tenencia por usuario autenticado.",
     "", "1", "", "Pendiente", "servicio-empresas", "2; 8; 15", "epica"),
    ("E3", "Épica", "E3 — Publicaciones de materiales", "", "", "",
     "Publicar, consultar y gestionar el ciclo de vida de materiales reciclables.",
     "", "1", "", "Pendiente", "servicio-materiales", "2; 8; 15", "epica"),
    ("E4", "Épica", "E4 — Mercado circular", "", "", "",
     "Catálogo público, solicitudes e intercambio entre empresas.",
     "", "2", "", "Pendiente", "servicio-emparejamiento; servicio-materiales", "2; 8; 13; 15", "epica"),
    ("E5", "Épica", "E5 — Plataforma nativa de la nube", "", "", "",
     "Contenedores, configuración externa, puerta de enlace, integración continua y paridad de entornos.",
     "", "1", "", "Pendiente", "puerta-enlace-api; plataforma", "1; 3; 4; 5; 7; 9; 11; 12; 13", "epica"),
    ("E6", "Épica", "E6 — Observabilidad y operaciones", "", "", "",
     "Registros, métricas, trazas, salud y procesos administrativos.",
     "", "2", "", "Pendiente", "plataforma", "6; 7; 10; 14", "epica"),
]

FEATURES = [
    ("F1", "Funcionalidad", "F1 — Autenticación de usuarios", "E1", "", "",
     "Inicio de sesión con correo/contraseña y proveedor externo.", "", "1", "", "Pendiente",
     "servicio-identidad", "5; 15", "funcionalidad"),
    ("F2", "Funcionalidad", "F2 — Autorización y tenencia", "E1", "", "",
     "Token Bearer, rutas protegidas y aislamiento por uid.", "", "1", "", "Pendiente",
     "servicio-identidad", "2; 12; 15", "funcionalidad"),
    ("F3", "Funcionalidad", "F3 — Registro y consulta de empresas", "E2", "", "",
     "Crear y listar empresas del usuario autenticado.", "", "1", "", "Pendiente",
     "servicio-empresas", "2; 8; 15", "funcionalidad"),
    ("F4", "Funcionalidad", "F4 — Administración de empresas", "E2", "", "",
     "Editar, eliminar y ver detalle de empresa.", "", "2", "", "Pendiente",
     "servicio-empresas", "2; 15", "funcionalidad"),
    ("F5", "Funcionalidad", "F5 — Publicación de materiales", "E3", "", "",
     "Crear publicaciones asociadas a una empresa propia.", "", "1", "", "Pendiente",
     "servicio-materiales", "2; 8; 15", "funcionalidad"),
    ("F6", "Funcionalidad", "F6 — Ciclo de vida de materiales", "E3", "", "",
     "Editar, cambiar estado y consultar publicaciones propias.", "", "1", "", "Pendiente",
     "servicio-materiales", "2; 8; 15", "funcionalidad"),
    ("F7", "Funcionalidad", "F7 — Catálogo público y búsqueda", "E4", "", "",
     "Descubrir materiales de otras empresas con filtros.", "", "2", "", "Pendiente",
     "servicio-materiales", "2; 13; 15", "funcionalidad"),
    ("F8", "Funcionalidad", "F8 — Solicitudes de intercambio", "E4", "", "",
     "Pedir, aceptar, rechazar y cerrar un intercambio.", "", "2", "", "Pendiente",
     "servicio-emparejamiento", "2; 8; 15", "funcionalidad"),
    ("F9", "Funcionalidad", "F9 — Configuración y secretos", "E5", "", "",
     "Variables de entorno; ningún secreto en el código.", "", "1", "", "Pendiente",
     "plataforma", "5; 8; 9", "funcionalidad"),
    ("F10", "Funcionalidad", "F10 — Contenerización y orquestación", "E5", "", "",
     "Imágenes Docker y ejecución local reproducible.", "", "1", "", "Pendiente",
     "plataforma", "3; 4; 7; 11", "funcionalidad"),
    ("F11", "Funcionalidad", "F11 — Contratos API y puerta de enlace", "E5", "", "",
     "APIs REST versionadas y puerta de entrada única.", "", "2", "", "Pendiente",
     "puerta-enlace-api", "2; 11; 15", "funcionalidad"),
    ("F12", "Funcionalidad", "F12 — Telemetría, registros y salud", "E6", "", "",
     "Salud, registros en la salida estándar, métricas y trazas.", "", "2", "", "Pendiente",
     "plataforma", "6; 7; 14", "funcionalidad"),
]

# id, type, title, epica, funcionalidad, story, description, ac, pri, sp, sprint, ms, factors, tags
STORIES = [
    ("US-01", "Historia de usuario",
     "US-01 — Iniciar sesión con correo y contraseña",
     "E1", "F1",
     "Como empresario, quiero iniciar sesión con correo y contraseña, para acceder de forma segura a mis empresas y materiales.",
     "Ver 02-historias-sprint-1.md (éxito, validaciones, errores, auth, reglas).",
     "Dado usuario Firebase válido. Cuando inicia sesión. Entonces entra a /home. Sin sesión: rutas protegidas redirigen a /login. Credenciales inválidas: mensaje de error. Claves Firebase por entorno.",
     "1", "5", "Sprint 1", "servicio-identidad; cliente-web", "5; 15",
     "sprint-1; servicio-identidad; factor-5; factor-15"),
    ("US-02", "Historia de usuario",
     "US-02 — Validar token y aislar datos en la API",
     "E1", "F2",
     "Como empresario, quiero que la API valide mi token y aísle mis datos, para que nadie más consulte o modifique mi información.",
     "Ver 02-historias-sprint-1.md.",
     "Dado Bearer válido: 200 solo de mis recursos. Sin token o token inválido: 401. Salud pública. uid del token es la tenencia. Proceso sin estado.",
     "1", "5", "Sprint 1", "servicio-identidad; servicio-empresas; servicio-materiales", "2; 12; 15",
     "sprint-1; servicio-identidad; factor-2; factor-12; factor-15"),
    ("US-03", "Historia de usuario",
     "US-03 — Registrar empresa",
     "E2", "F3",
     "Como empresario, quiero registrar mi empresa (nombre, NIT, ciudad, sector, descripción y comunidad), para asociar publicaciones de materiales a un actor formal.",
     "Ver 02-historias-sprint-1.md.",
     "POST /api/companies/ autenticado persiste en MongoDB Atlas y responde 201. Validar name/nit/city. 401 sin token. owner_uid siempre del token.",
     "1", "5", "Sprint 1", "servicio-empresas; cliente-web", "2; 5; 8; 15",
     "sprint-1; servicio-empresas; factor-2; factor-8; factor-15"),
    ("US-04", "Historia de usuario",
     "US-04 — Consultar mis empresas",
     "E2", "F3",
     "Como empresario, quiero consultar las empresas que yo registré, para verificar y reutilizar esos datos al publicar materiales.",
     "Ver 02-historias-sprint-1.md.",
     "GET /api/companies/ lista solo owner_uid=uid. Estado vacío si no hay empresas. 401 sin sesión. Usuario A no ve empresas de B.",
     "1", "3", "Sprint 1", "servicio-empresas; cliente-web", "2; 8; 15",
     "sprint-1; servicio-empresas; factor-2; factor-8; factor-15"),
    ("US-05", "Historia de usuario",
     "US-05 — Publicar material reciclable",
     "E3", "F5",
     "Como empresario, quiero publicar un material reciclable asociado a una de mis empresas, para ofrecer excedente a la red circular.",
     "Ver 02-historias-sprint-1.md.",
     "POST /api/materials/ 201. Cantidad > 0, precio >= 0, empresa propia. Sin empresas: la interfaz bloquea el envío. company_id ajeno: 403/400. estado inicial disponible.",
     "1", "5", "Sprint 1", "servicio-materiales; cliente-web", "2; 8; 15",
     "sprint-1; servicio-materiales; factor-2; factor-8; factor-15"),
    ("US-06", "Historia de usuario",
     "US-06 — Consultar mis publicaciones de materiales",
     "E3", "F6",
     "Como empresario, quiero ver las publicaciones de materiales de mis empresas, para conocer el inventario que tengo en la plataforma.",
     "Ver 02-historias-sprint-1.md.",
     "GET /api/materials/ solo materiales de empresas del uid. Vacío no es error. 401 sin sesión. Catálogo público queda fuera (US-16).",
     "1", "3", "Sprint 1", "servicio-materiales; cliente-web", "2; 8; 15",
     "sprint-1; servicio-materiales; factor-2; factor-8; factor-15"),
    ("US-07", "Historia de usuario",
     "US-07 — Configuración externa, contenedores y salud",
     "E5", "F9",
     "Como operador, quiero configurar la aplicación con variables de entorno, ejecutarla en contenedores y verificar su salud, para correr el mismo incremento en local sin secretos en el código.",
     "Ver 02-historias-sprint-1.md.",
     "Salud 200. Variables de entorno obligatorias. Secretos fuera del código. docker compose up verificable. MongoDB Atlas y Firebase como servicios de respaldo.",
     "1", "8", "Sprint 1", "plataforma", "3; 4; 5; 7; 8; 9; 11; 14",
     "sprint-1; plataforma; factor-5; factor-8; factor-14"),
    ("US-08", "Historia de usuario",
     "US-08 — Crear cuenta con correo y contraseña",
     "E1", "F1",
     "Como visitante, quiero crear una cuenta con correo y contraseña, para usar la plataforma sin depender de un usuario preexistente.",
     "Ver 03-criterios-backlog-completo.md.",
     "Registro Firebase con email nuevo y contraseña de al menos 6 caracteres. Correo duplicado o contraseña corta: error. Tras registro, sesión en /home.",
     "2", "5", "Sprint 2", "servicio-identidad; cliente-web", "5; 15",
     "sprint-2; servicio-identidad; factor-15"),
    ("US-09", "Historia de usuario",
     "US-09 — Iniciar sesión con Google",
     "E1", "F1",
     "Como empresario, quiero iniciar sesión con Google, para autenticarme más rápido.",
     "Ver 03-criterios-backlog-completo.md.",
     "Ventana de Google exitoso entra a /home. Cancelación o fallo: mensaje en /login.",
     "2", "3", "Sprint 2", "servicio-identidad; cliente-web", "5; 8; 15",
     "sprint-2; servicio-identidad; factor-8; factor-15"),
    ("US-10", "Historia de usuario",
     "US-10 — Editar empresa propia",
     "E2", "F4",
     "Como empresario, quiero editar los datos de una empresa mía, para mantener la información actualizada.",
     "Ver 03-criterios-backlog-completo.md.",
     "PUT propio 200. PUT ajeno 403/404. Nombre vacío 400.",
     "2", "3", "Sprint 2", "servicio-empresas", "2; 15",
     "sprint-2; servicio-empresas; factor-2; factor-15"),
    ("US-11", "Historia de usuario",
     "US-11 — Eliminar empresa propia",
     "E2", "F4",
     "Como empresario, quiero eliminar una empresa mía, para retirar actores que ya no participan.",
     "Ver 03-criterios-backlog-completo.md.",
     "DELETE propio 204. Ajeno 403/404. Materiales asociados: 409 o cascada documentada.",
     "2", "3", "Sprint 2", "servicio-empresas", "2; 15",
     "sprint-2; servicio-empresas; factor-2; factor-15"),
    ("US-12", "Historia de usuario",
     "US-12 — Editar publicación de material",
     "E3", "F6",
     "Como empresario, quiero editar una publicación de material mía, para corregir cantidad, precio o ubicación.",
     "Ver 03-criterios-backlog-completo.md.",
     "PUT propio con cantidad > 0. Cantidad inválida 400. Ajeno 403/404.",
     "2", "3", "Sprint 2", "servicio-materiales", "2; 15",
     "sprint-2; servicio-materiales; factor-2; factor-15"),
    ("US-13", "Historia de usuario",
     "US-13 — Cambiar estado del material",
     "E3", "F6",
     "Como empresario, quiero cambiar el estado de un material (available, reserved, exchanged), para reflejar su ciclo de vida.",
     "Ver 03-criterios-backlog-completo.md.",
     "available→reserved por dueño. Estado inválido 400. No dueño 403.",
     "2", "5", "Sprint 2", "servicio-materiales", "2; 15",
     "sprint-2; servicio-materiales; factor-2; factor-15"),
    ("US-14", "Historia de usuario",
     "US-14 — Ver detalle de empresa y material",
     "E2", "F4",
     "Como empresario, quiero ver el detalle de una empresa y de un material, para revisar la información completa antes de operar.",
     "Ver 03-criterios-backlog-completo.md.",
     "GET por id propio muestra todos los campos. Id inexistente 404. Ajeno privado 403/404.",
     "2", "3", "Sprint 2", "servicio-empresas; servicio-materiales", "2",
     "sprint-2; factor-2"),
    ("US-15", "Historia de usuario",
     "US-15 — Validaciones de negocio en la API",
     "E1", "F2",
     "Como empresario, quiero que la API rechace datos inválidos y acciones sobre recursos ajenos, para no corromper el negocio ni cruzar tenencias.",
     "Ver 03-criterios-backlog-completo.md.",
     "NIT duplicado por uid 409. company_id ajeno 403. owner_uid del body se ignora.",
     "2", "5", "Sprint 2", "servicio-empresas; servicio-materiales", "2; 15",
     "sprint-2; factor-2; factor-15"),
    ("US-16", "Historia de usuario",
     "US-16 — Catálogo público de materiales disponibles",
     "E4", "F7",
     "Como interesado, quiero ver un catálogo de materiales disponibles de otras empresas, para encontrar recursos reutilizables.",
     "Ver 03-criterios-backlog-completo.md.",
     "Autenticado ve available ajenos. reserved/exchanged no aparecen. Sin token 401.",
     "2", "8", "Sprint 3", "servicio-materiales; cliente-web", "2; 15",
     "sprint-3; servicio-materiales; factor-2; factor-15"),
    ("US-17", "Historia de usuario",
     "US-17 — Filtrar catálogo por tipo, ciudad y precio",
     "E4", "F7",
     "Como interesado, quiero filtrar el catálogo por tipo, ciudad y rango de precio, para acotar resultados útiles.",
     "Ver 03-criterios-backlog-completo.md.",
     "Filtros combinados acotan resultados. Rango invertido 400. Sin coincidencias: lista vacía.",
     "2", "5", "Sprint 3", "servicio-materiales", "2; 13",
     "sprint-3; servicio-materiales; factor-2; factor-13"),
    ("US-18", "Historia de usuario",
     "US-18 — Solicitar un material disponible",
     "E4", "F8",
     "Como interesado, quiero solicitar un material disponible, para iniciar un intercambio con su publicador.",
     "Ver 03-criterios-backlog-completo.md.",
     "POST crea solicitud pendiente. Propio o no available: 409. Duplicado pending: 409. Requiere auth.",
     "2", "8", "Sprint 3", "servicio-emparejamiento", "2; 8; 15",
     "sprint-3; servicio-emparejamiento; factor-2; factor-8; factor-15"),
    ("US-19", "Historia de usuario",
     "US-19 — Aceptar o rechazar solicitudes",
     "E4", "F8",
     "Como empresario, quiero aceptar o rechazar solicitudes sobre mis materiales, para controlar con quién intercambio.",
     "Ver 03-criterios-backlog-completo.md.",
     "Dueño acepta: accepted + material reserved. No dueño 403. No pending 409.",
     "2", "5", "Sprint 3", "servicio-emparejamiento", "2; 15",
     "sprint-3; servicio-emparejamiento; factor-2; factor-15"),
    ("US-20", "Historia de usuario",
     "US-20 — Cerrar intercambio",
     "E4", "F8",
     "Como empresario, quiero marcar un intercambio como cerrado, para retirar el material del catálogo y dejar trazabilidad.",
     "Ver 03-criterios-backlog-completo.md.",
     "Cierre: material exchanged y solicitud completada. Estado incorrecto 409. Ajeno 403.",
     "2", "5", "Sprint 3", "servicio-emparejamiento; servicio-materiales", "2; 8; 12",
     "sprint-3; servicio-emparejamiento; factor-2; factor-8; factor-12"),
    ("US-21", "Historia de usuario",
     "US-21 — Registros estructurados en la salida estándar",
     "E6", "F12",
     "Como operador, quiero registros estructurados en la salida estándar de cada servicio, para diagnosticar sin entrar al contenedor.",
     "Ver 03-criterios-backlog-completo.md.",
     "Cada petición emite log a la salida estándar con método, ruta y status. Sin token ni secretos. 5xx en nivel ERROR.",
     "2", "5", "Sprint 4", "plataforma", "6; 14",
     "sprint-4; plataforma; factor-6; factor-14"),
    ("US-22", "Historia de usuario",
     "US-22 — Métricas y trazas de las APIs",
     "E6", "F12",
     "Como operador, quiero métricas y trazas de las APIs (latencia, errores, correlación), para observar el sistema en la nube.",
     "Ver 03-criterios-backlog-completo.md.",
     "Métricas de requests/latencia/errores. Telemetría degradable si no hay cadena de conexión.",
     "2", "8", "Sprint 4", "plataforma", "14",
     "sprint-4; plataforma; factor-14"),
    ("US-23", "Historia de usuario",
     "US-23 — Separar servicio-empresas y servicio-materiales",
     "E5", "F10",
     "Como operador, quiero separar empresas y materiales en microservicios contenerizados, para desplegarlos y escalarlos de forma independiente.",
     "Ver 03-criterios-backlog-completo.md.",
     "Dos imágenes/puertos. La caída de materiales no tumba empresas. Sin import de código cruzado.",
     "2", "13", "Sprint 4", "servicio-empresas; servicio-materiales", "1; 2; 7; 12; 13",
     "sprint-4; servicio-empresas; servicio-materiales; factor-1; factor-13"),
    ("US-24", "Historia de usuario",
     "US-24 — puerta de enlace de API",
     "E5", "F11",
     "Como cliente web, quiero consumir los servicios a través de una puerta de enlace de API, para unificar autenticación, enrutamiento y CORS.",
     "Ver 03-criterios-backlog-completo.md.",
     "La puerta de enlace enruta /api/companies y /api/materials. Ruta inexistente: 404. CORS no permitido se rechaza.",
     "2", "8", "Sprint 4", "puerta-enlace-api", "2; 11; 15",
     "sprint-4; puerta-enlace-api; factor-2; factor-11; factor-15"),
    ("US-25", "Historia de usuario",
     "US-25 — Pipeline diseño-compilación-publicación-ejecución",
     "E5", "F10",
     "Como operador, quiero un canal de diseño, compilación, publicación y ejecución, para publicar artefactos inmutables con la misma receta en local y nube.",
     "Ver 03-criterios-backlog-completo.md.",
     "CI construye imagen versionada. Run solo inyecta env/secretos. No recompilar en producción.",
     "2", "8", "Sprint 4", "plataforma", "3; 4; 9",
     "sprint-4; plataforma; factor-3; factor-4; factor-9"),
    ("US-26", "Historia de usuario",
     "US-26 — Sondas de actividad y de preparación",
     "E6", "F12",
     "Como operador, quiero sondas de actividad y de preparación, para que el orquestador reinicie o retire instancias no saludables.",
     "Ver 03-criterios-backlog-completo.md.",
     "La preparación falla si Atlas no responde. La actividad refleja proceso vivo. El reinicio recrea instancia.",
     "3", "3", "Sprint 4", "plataforma", "7; 11; 14",
     "sprint-4; plataforma; factor-7; factor-11; factor-14"),
    ("US-27", "Historia de usuario",
     "US-27 — Sugerencias de emparejamiento",
     "E4", "F7",
     "Como interesado, quiero recibir sugerencias de materiales según ciudad y tipo, para descubrir intercambios viables más rápido.",
     "Ver 03-criterios-backlog-completo.md.",
     "Sugerencias available ajenas por ciudad/tipo. Sin coincidencias: lista vacía. Requiere auth.",
     "3", "8", "Sprint 5", "servicio-emparejamiento", "2; 13",
     "sprint-5; servicio-emparejamiento; factor-2; factor-13"),
    ("US-28", "Historia de usuario",
     "US-28 — Notificaciones de solicitudes",
     "E4", "F8",
     "Como empresario, quiero recibir notificaciones de nuevas solicitudes, para responder sin vigilar el tablero.",
     "Ver 03-criterios-backlog-completo.md.",
     "Al crear la solicitud, notificación para el dueño. Listar notificaciones exige 401 si no hay token.",
     "3", "8", "Sprint 5", "servicio-notificaciones", "2; 6; 14",
     "sprint-5; servicio-notificaciones; factor-6; factor-14"),
    ("US-29", "Historia de usuario",
     "US-29 — Impacto estimado en kg reutilizados",
     "E3", "F6",
     "Como empresario, quiero ver el impacto estimado (kg reutilizados) de mis intercambios, para evidenciar el valor circular.",
     "Ver 03-criterios-backlog-completo.md.",
     "Suma quantity de exchanged propios. Sin cierres: 0. Requiere auth.",
     "3", "5", "Sprint 5", "servicio-materiales", "2; 14",
     "sprint-5; servicio-materiales; factor-2; factor-14"),
    ("US-30", "Historia de usuario",
     "US-30 — Proceso administrativo de carga inicial",
     "E6", "F9",
     "Como operador, quiero ejecutar un proceso administrativo de carga inicial sin acoplarlo al proceso web en ejecución, para cargar datos de demo de forma repetible.",
     "Ver 03-criterios-backlog-completo.md.",
     "Comando independiente con las mismas variables de entorno. No bloquea el proceso HTTP. Idempotencia documentada.",
     "3", "2", "Sprint 5", "plataforma", "10",
     "sprint-5; plataforma; factor-10"),
]

HEADERS = [
    "ID",
    "Tipo de elemento",
    "Título",
    "Épica",
    "Funcionalidad",
    "Descripción",
    "Criterios de aceptación",
    "Prioridad",
    "Puntos de historia",
    "Sprint",
    "Microservicio",
    "Factores nativos de la nube",
    "Etiquetas",
]


def row_from(item):
    # epicas/funcionalidads: 13 fields already matching-ish
    if len(item) == 13:
        ident, wtype, title, epica, funcionalidad, _story, desc, ac, pri, sp, sprint, ms, tags = item
        description = desc
        factors = ""
        # last of epicas was tags, factors packed in ms field for epicas? handle separately
        return None
    return item


def write_backlog():
    path = OUT / "product-backlog.csv"
    with path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(HEADERS)
        for e in EPICS:
            ident, wtype, title, epica, funcionalidad, story, desc, ac, pri, sp, sprint, ms, factors, tags = e
            writer.writerow([ident, wtype, title, epica, funcionalidad, desc, ac, pri, sp, sprint, ms, factors, tags])
        for f in FEATURES:
            ident, wtype, title, epica, funcionalidad, story, desc, ac, pri, sp, sprint, ms, factors, tags = f
            writer.writerow([ident, wtype, title, epica, funcionalidad, desc, ac, pri, sp, sprint, ms, factors, tags])
        for s in STORIES:
            ident, wtype, title, epica, funcionalidad, story, desc, ac, pri, sp, sprint, ms, factors, tags = s
            writer.writerow([ident, wtype, title, epica, funcionalidad, story, ac, pri, sp, sprint, ms, factors, tags])
    print("wrote", path)


FACTORS = [
    ("1", "Un código base, una aplicación", "Un repositorio; cada microservicio es una aplicación.", "US-23", "E5", "Sprint 4"),
    ("2", "API primero", "Toda interacción de negocio por REST.", "US-02 a US-06, US-10 a US-20, US-24", "F11", "Sprint 1+"),
    ("3", "Gestión de dependencias", "Dependencias declaradas e imagen Docker.", "US-07, US-25", "F10", "Sprint 1, 4"),
    ("4", "Diseño, compilación, publicación y ejecución", "La compilación de la imagen se separa de la ejecución con variables de entorno.", "US-07, US-25", "F10", "Sprint 1, 4"),
    ("5", "Configuración, credenciales y código", "Secretos y configuración solo por entorno.", "US-01, US-03, US-07", "F9", "Sprint 1"),
    ("6", "Registros", "Los registros salen como flujo hacia la salida estándar.", "US-21, US-28", "F12", "Sprint 4, 5"),
    ("7", "Desechabilidad", "Contenedores que arrancan y mueren rápido.", "US-07, US-23, US-26", "F10", "Sprint 1, 4"),
    ("8", "Servicios de respaldo", "MongoDB Atlas y Firebase conectables por URL.", "US-03 a US-06, US-09, US-18, US-20", "E2 E3", "Sprint 1+"),
    ("9", "Paridad de entornos", "Misma receta local y nube.", "US-07, US-25", "E5", "Sprint 1, 4"),
    ("10", "Procesos administrativos", "Carga inicial independiente fuera de la petición HTTP.", "US-30", "E6", "Sprint 5"),
    ("11", "Enlace de puertos", "Servicios expuestos por puerto.", "US-07, US-24, US-26", "F10 F11", "Sprint 1, 4"),
    ("12", "Procesos sin estado", "Estado en Atlas/Firebase, no en memoria.", "US-02, US-20, US-23", "F2", "Sprint 1, 3, 4"),
    ("13", "Concurrencia", "Escalar catálogo y emparejamiento de forma independiente.", "US-17, US-23, US-27", "E4 E5", "Sprint 3, 4, 5"),
    ("14", "Telemetría", "Salud, métricas, trazas e impacto.", "US-07, US-21, US-22, US-26, US-29", "F12", "Sprint 1, 4, 5"),
    ("15", "Autenticación y autorización", "Identidad y tenencia desde el Sprint 1.", "US-01, US-02, US-08, US-09, US-15, US-16, US-24", "E1", "Sprint 1+"),
]


def write_matrix():
    path = OUT / "matriz-15-factores.csv"
    with path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "Factor #", "Nombre", "Aplicación en EcoRed", "Historias",
            "Épica / Funcionalidad", "Sprint donde aparece", "Cubierto en Sprint 1",
        ])
        sprint1 = {
            "2", "3", "4", "5", "7", "8", "9", "11", "12", "14", "15",
        }
        for num, name, app, stories, epica, sprint in FACTORS:
            writer.writerow([num, name, app, stories, epica, sprint, "Sí" if num in sprint1 else "Parcial / posterior"])
    print("wrote", path)


if __name__ == "__main__":
    write_backlog()
    write_matrix()
